// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4IJayhDsBBhx_nzMRx5hzsebJCfhngSc',
    appId: '1:536896610923:web:f74007e66a9b9ea466c72e',
    messagingSenderId: '536896610923',
    projectId: 'tugymroutine',
    authDomain: 'tugymroutine.firebaseapp.com',
    storageBucket: 'tugymroutine.appspot.com',
    measurementId: 'G-CPJN7LCPKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLRHZTZ_yaojfSXPFYMnYN0lni_LgHoe0',
    appId: '1:536896610923:android:323c55fb84af478a66c72e',
    messagingSenderId: '536896610923',
    projectId: 'tugymroutine',
    storageBucket: 'tugymroutine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA441UPBHUH-g2qEFTGfVyNy_78h6D_pbo',
    appId: '1:536896610923:ios:3f2af9affde2b27a66c72e',
    messagingSenderId: '536896610923',
    projectId: 'tugymroutine',
    storageBucket: 'tugymroutine.appspot.com',
    iosBundleId: 'com.example.tuGymRoutine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA441UPBHUH-g2qEFTGfVyNy_78h6D_pbo',
    appId: '1:536896610923:ios:c912571894d2903866c72e',
    messagingSenderId: '536896610923',
    projectId: 'tugymroutine',
    storageBucket: 'tugymroutine.appspot.com',
    iosBundleId: 'com.example.tuGymRoutine.RunnerTests',
  );
}
